### ISSUE TITLE
Текст вылазит за границы поля ввода при вводе эмоций

### ISSUE THREAD

**Issue by romchik-gromchik** [mshurkaeu-public/i-care.by#2]
![20230320_112207.jpg](https://user-images.githubusercontent.com/128365285/226312326-aeeb08dc-0dee-417a-b43b-1250d2ff5402.jpg)

**Comment by mshurkaeu-public** [comment]
Гэта памылка ў кампаненце flutter. Я паведаміў распрацоўшчыкам flutter пра гэтую памылку - [flutter #123101](https://github.com/flutter/flutter/issues/123101).

А зараз патрэбна прыдумаць, што рабіць пакуль памылку не паправяць. Напэўна, змяню інтэрфейс. Змяню hintText на helperText і дадам SingleChildScrollView.

**Comment by mshurkaeu-public** [comment]
Зрабіў абыход да знойдзенага бага для палёў увода эмоцый і адчуванняў. Такая ж самая праблема можа ўзнікнуць у палях увода для таго, што чалавек жадае зрабіць. Але там падказка больш кароткая і таму верагоднасць праблемы ніжэй. Пакуль што пакіну тыя палі як ёсць. Тэкст-падказка ўнутры поля так сама мае сэнс. Спадзяюся, што распрацоўшчыкі flutter хутка выправяць памылку ў TextField.

Зараз замест падказкі ўнутры поля ўвода эмоцый і адчуванняў падказка будзе з'яўляцца, калі чалавек будзе націскаць на пытанне "Што адчуваеш? Як ты?". Для падказкі, што на гэтае пытанне можна націснуць, я дадаў сымбал 🤔. Спадзяюся, гэта больш-менш зразумелая падказка.

![Screenshot from 2023-03-22 12-08-24](https://user-images.githubusercontent.com/113517149/226886920-ba410b03-d4f0-491d-825c-d17f1b81ff16.png)
